# Generated by Django 5.0.4 on 2024-08-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedElection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('candidates', models.JSONField(blank=True, null=True)),
                ('topics', models.JSONField(blank=True, null=True)),
                ('tally', models.IntegerField()),
            ],
            options={
                'db_table': 'completed_elections',
            },
        ),
        migrations.AlterField(
            model_name='encryptedtally',
            name='election_id',
            field=models.IntegerField(),
        ),
    ]
